(define (problem apartment-problem)
(:domain apartment)
(:objects kitchen diningroom livingroom bedroom storage bathroom - room
          cup pan plate notebook bottle remote book phone keys towel - object)
(:init
  (room kitchen)
  (room diningroom)
  (room livingroom)
  (room bedroom)
  (room storage)
  (room bathroom)
  (robot-at livingroom)
  (object cup)
  (at cup kitchen)
  (object pan)
  (at pan kitchen)
  (object plate)
  (at plate diningroom)
  (object notebook)
  (at notebook diningroom)
  (object bottle)
  (at bottle livingroom)
  (object remote)
  (at remote livingroom)
  (object book)
  (at book bedroom)
  (object phone)
  (at phone bedroom)
  (object keys)
  (at keys storage)
  (object towel)
  (at towel bathroom)
  (connected storage bedroom)
  (connected bedroom storage)
  (connected livingroom bedroom)
  (connected bedroom livingroom)
  (connected livingroom diningroom)
  (connected diningroom livingroom)
  (connected bathroom diningroom)
  (connected diningroom bathroom)
  (connected diningroom kitchen)
  (connected kitchen diningroom)
  (handempty)
)
(:goal (and (robot-at dining)))
)